apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mongodb
spec:
  replicas: 1 # 1 pod (note: every pod is independent to each other)
  selector:
    matchLabels:
      app: mongodb
  template: # configuration for a mongodb container wrapped in a pod
    metadata: 
      labels: 
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports: 
            - containerPort: 27017
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests: 
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: # an alternative to 'httpGet' and is used when you want to check the health or readiness
              port: 27017
          readinessProbe: # pods are excluded from the set of endpoints used by Services or load balancers until it becomes ready
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 3
            failureThreshold: 1
            tcpSocket:
              port: 27017