apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-rabbitmq"
spec:
  replicas: 1 # 1 pod (note: every pod is independent to each other)
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-rabbitmq"
  template: # configuration for a rabbitmq container wrapped in a pod
    metadata:
      labels:
        app: "{{ .Release.Name }}-rabbitmq"
    spec:
      containers:
        - name: "{{ .Release.Name }}-rabbitmq"
          image: rabbitmq:3.9.18-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: # an alternative to 'httpGet' and is used when you want to check the health or readiness
              port: 5672
          readinessProbe: # pods are excluded from the set of endpoints used by Services or load balancers until it becomes ready
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 3
            failureThreshold: 1
            tcpSocket:
              port: 5672
