apiVersion: v1
kind: Service
metadata:
  name: my-rabbitmq
spec:
  selector: # the service is applied to pods whose label equals to "app: rabbitmq"
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: rabbitmq
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
