apiVersion: v1
kind: Service
metadata:
  name: my-server
spec:
  selector: # the service is applied to pods whose label equals to "app: server"
    app: server
  type: ClusterIP
  ports:
    - name: server
      port: 30005
      targetPort: 30005
