apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
spec:
  replicas: 1 # 1 pod (note: every pod is independent to each other)
  selector:
    matchLabels:
      app: server
  template: # configuration for the server container wrapped in a pod
    metadata:
      labels:
        app: server
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nc -z my-rabbitmq 5672; do echo `date`; sleep 1; done",
            ]
        - name: wait-for-mongodb
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "until nc -z my-mongodb 27017; do echo `date`; sleep 1; done",
            ]
      containers:
        - name: server
          image: kevin228839/youbike-crawler:v3
          ports:
            - containerPort: 30005
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            tcpSocket: # an alternative to 'httpGet' and is used when you want to check the health or readiness
              port: 30005
          readinessProbe: # pods are excluded from the set of endpoints used by Services or load balancers until it becomes ready
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 3
            failureThreshold: 1
            tcpSocket:
              port: 30005
